drone:
  token: LIHSKAvytiKdtZKQPdr7nSIU6uBxnGel
  url: https://ci.build.loyalty.virgin.com
  organization: virgin-loyalty
github:
  token: 0fdabaff09d4fd13800cad2a2a32f324ca796d5d
  url: https://api.github.com/
  organization: virgin-loyalty
  repositoryPrefix: "red-"

server:
  port: 8080

blacklist: >
  example-repos,
  red-api-external,
  red-scripts,
  red-metric-export-test,
  red-poc-fp-parser,
  red-vaa-campaign-ingestion,
  red-octopus-txn-processor
