drone:
  token: LIHSKAvytiKdtZKQPdr7nSIU6uBxnGel
  url: https://ci.build.loyalty.virgin.com
  organization: virgin-loyalty
github:
  token: 8193be1213c8fb17031962f796d3c525801ea67f
  url: https://api.github.com/
  organization: virgin-loyalty
  repositoryPrefix: "red-"

server:
  port: 8080

blacklist: >
  example-repos,
  red-api-external,
  red-scripts,
  red-metric-export-test,
  red-poc-fp-parser,
  red-vaa-campaign-ingestion
